services:
  mt5docker:
    image: hpdeandrade/mt5docker:5.0.4993
    container_name: mt5docker
    environment:
      - MT5_HOST=
      - VNC_PW=
    ports:
      - 5901:5901
      - 6081:6081
      - 8001:8001
    restart: "no"
    stdin_open: true
    tty: true